version: "4.27.2"

services:
  database:
    image: postgres
    container_name: PetRegister
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=pstvadmin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ciadb
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
